import { useEffect, useId, useMemo, useRef, useState } from 'react';
import { cx } from '@/components/react/cx';

export interface BetSizingPathsProps {
  /** Heading above the chart. */
  title?: string;
  /** Label for the win-probability slider. */
  probLabel?: string;
  /** Label for the reshuffle / new-sequence button. */
  reshuffleLabel?: string;
  /** Legend/readout label for the half-Kelly bettor. */
  halfLabel?: string;
  /** Legend/readout label for the full-Kelly bettor. */
  fullLabel?: string;
  /** Legend/readout label for the over-betting bettor. */
  overLabel?: string;
  /** Label for the starting-bankroll reference line. */
  startLabel?: string;
  /** Suffix appended to a bankroll multiple readout (e.g. "6.2×"). */
  multipleSuffix?: string;
  /** One-line takeaway shown under the chart. */
  caption?: string;
  /** Win probability of the favorable bet, as a fraction (0.52–0.70). Defaults to `0.6`. */
  p?: number;
  /** Seed for the deterministic outcome sequence. Defaults to `12345`. */
  seed?: number;
  className?: string;
}

const prefersReducedMotion = (): boolean =>
  typeof window !== 'undefined' &&
  typeof window.matchMedia === 'function' &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const BETS = 60; // number of bets in the shared sequence
const START = 1.0; // starting bankroll for every bettor

// Deterministic PRNG — mulberry32. Seeded so the sequence is reproducible and
// never touches Math.random (forbidden in the build sandbox).
const mulberry32 = (seed: number): (() => number) => {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};

// One shared sequence of win/loss outcomes for a given p and seed.
const makeOutcomes = (p: number, seed: number): boolean[] => {
  const rand = mulberry32(seed);
  const out: boolean[] = [];
  for (let i = 0; i < BETS; i++) out.push(rand() < p);
  return out;
};

// Walk a bankroll through the shared outcomes at a fixed betting fraction.
// Even-money bet: win multiplies by (1 + f), loss multiplies by (1 − f).
const runBettor = (outcomes: boolean[], fraction: number): number[] => {
  const path: number[] = [START];
  let bank = START;
  for (const win of outcomes) {
    bank *= win ? 1 + fraction : 1 - fraction;
    path.push(bank);
  }
  return path;
};

/**
 * Three bankroll trajectories over the SAME shared sequence of random bet
 * outcomes, sized differently — half-Kelly, full-Kelly, and over-betting (2×
 * Kelly). For a favorable even-money bet with win probability p, full Kelly is
 * f* = 2p − 1. Every bettor starts at a bankroll of 1.0 and multiplies by
 * (1 + f) on a win and (1 − f) on a loss across the identical outcome string,
 * so the difference on screen is purely the bet size. Plotted on a log y-axis
 * so a steady grower and a collapsing over-bettor coexist. The outcome string
 * is generated by a deterministic seeded PRNG (mulberry32); the win-probability
 * slider recomputes f* and the "new sequence" button bumps the seed — both stay
 * fully reproducible. Curves draw in left-to-right on mount/change, respecting
 * `prefers-reduced-motion` (jumps to the final curves).
 */
export function BetSizingPaths({
  title = 'Same flips, three bet sizes',
  probLabel = 'Win probability p',
  reshuffleLabel = 'New sequence',
  halfLabel = 'Half Kelly',
  fullLabel = 'Full Kelly',
  overLabel = 'Over-betting',
  startLabel = 'Start',
  multipleSuffix = '×',
  caption = 'Same coin, same flips — three bet sizes. Half-Kelly climbs steadily. Full-Kelly grows faster but lurches through gut-wrenching drawdowns. The over-bettor shoots up, then a normal losing streak wipes them out: past twice Kelly, ruin is mathematically certain.',
  p = 0.6,
  seed = 12345,
  className,
}: BetSizingPathsProps) {
  const id = useId();
  const [pPct, setPPct] = useState(Math.round(p * 100));
  const [seedBump, setSeedBump] = useState(0);
  const [progress, setProgress] = useState(0); // 0 → 1 reveal animation
  const rafRef = useRef<number | null>(null);

  const pVal = pPct / 100;
  const kelly = Math.max(0, 2 * pVal - 1); // full Kelly fraction for even money

  const fractions = useMemo(
    () => ({
      half: 0.5 * kelly,
      full: kelly,
      over: 2 * kelly,
    }),
    [kelly],
  );

  const activeSeed = seed + seedBump;

  // Shared outcome sequence, then three bankroll paths over it.
  const paths = useMemo(() => {
    const outcomes = makeOutcomes(pVal, activeSeed);
    return {
      half: runBettor(outcomes, fractions.half),
      full: runBettor(outcomes, fractions.full),
      over: runBettor(outcomes, fractions.over),
    };
  }, [pVal, activeSeed, fractions.half, fractions.full, fractions.over]);

  const W = 560;
  const H = 260;
  const padLeft = 40;
  const padRight = 12;
  const padTop = 16;
  const padBottom = 26;

  // Reveal animation: sweep the curves in left-to-right.
  useEffect(() => {
    if (prefersReducedMotion()) {
      setProgress(1);
      return;
    }
    setProgress(0);
    const duration = 1000;
    let startTs: number | null = null;
    const stepFn = (ts: number) => {
      if (startTs === null) startTs = ts;
      const t = Math.min(1, (ts - startTs) / duration);
      const eased = 1 - (1 - t) * (1 - t); // easeOutQuad
      setProgress(eased);
      if (t < 1) rafRef.current = requestAnimationFrame(stepFn);
    };
    rafRef.current = requestAnimationFrame(stepFn);
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    };
  }, [paths]);

  // Log-scale y bounds across all three paths, guarding against ruin (→ 0).
  const allValues = [...paths.half, ...paths.full, ...paths.over];
  const FLOOR = 1e-4; // clamp so collapsing paths stay on a log axis
  let logMax = Math.log(START);
  let logMin = Math.log(START);
  for (const v of allValues) {
    const lv = Math.log(Math.max(v, FLOOR));
    if (lv > logMax) logMax = lv;
    if (lv < logMin) logMin = lv;
  }
  // Pad the range a touch and guard a degenerate span.
  const padLog = Math.max((logMax - logMin) * 0.06, 0.1);
  logMax += padLog;
  logMin -= padLog;
  if (logMax - logMin < 1e-3) {
    logMax = Math.log(START) + 1;
    logMin = Math.log(START) - 1;
  }

  const xToPx = (i: number) => padLeft + (i / BETS) * (W - padLeft - padRight);
  const yToPx = (v: number) => {
    const lv = Math.log(Math.max(v, FLOOR));
    return padTop + (1 - (lv - logMin) / (logMax - logMin)) * (H - padTop - padBottom);
  };

  const drawnBets = Math.max(1, Math.round(BETS * progress));

  const pathToD = (path: number[]): string => {
    let d = '';
    const last = Math.min(drawnBets, path.length - 1);
    for (let i = 0; i <= last; i++) {
      d += `${i === 0 ? 'M' : 'L'} ${xToPx(i).toFixed(2)} ${yToPx(path[i]).toFixed(2)} `;
    }
    return d.trim();
  };

  const finalOf = (path: number[]) => path[path.length - 1];
  const fmtMult = (v: number) =>
    `${v >= 100 ? Math.round(v) : v.toFixed(v < 10 ? 1 : 0)}${multipleSuffix}`;
  const fmtPct = (f: number) => `${Math.round(f * 100)}%`;

  const finalHalf = finalOf(paths.half);
  const finalFull = finalOf(paths.full);
  const finalOver = finalOf(paths.over);

  const startY = yToPx(START);
  const baseY = H - padBottom;

  const series = [
    {
      key: 'half',
      d: paths.half,
      color: 'var(--color-brand-500)',
      label: halfLabel,
      fraction: fractions.half,
      final: finalHalf,
      width: 2.4,
    },
    {
      key: 'full',
      d: paths.full,
      color: 'var(--color-accent-500)',
      label: fullLabel,
      fraction: fractions.full,
      final: finalFull,
      width: 2.2,
    },
    {
      key: 'over',
      d: paths.over,
      color: 'var(--color-ink-500)',
      label: overLabel,
      fraction: fractions.over,
      final: finalOver,
      width: 2,
    },
  ] as const;

  return (
    <figure
      className={cx(
        'my-6 rounded-card border border-ink-100 bg-surface p-5 shadow-soft',
        className,
      )}
    >
      <figcaption className="flex items-center justify-between gap-3">
        <span className="font-medium text-ink-900">{title}</span>
        <span className="rounded-pill bg-brand-600 px-3 py-1 text-sm font-medium text-white">
          {probLabel}: {pPct}%
        </span>
      </figcaption>

      {/* Legend */}
      <div className="mt-4 flex flex-wrap gap-4 text-sm">
        {series.map((s) => (
          <span key={s.key} className="inline-flex items-center gap-2 text-ink-700">
            <span
              className="h-1 w-5 rounded-pill"
              style={{ backgroundColor: s.color }}
              aria-hidden="true"
            />
            {`${s.label} (${fmtPct(s.fraction)})`}
          </span>
        ))}
      </div>

      <svg
        viewBox={`0 0 ${W} ${H}`}
        className="mt-3 w-full"
        role="img"
        aria-label={`Three bankroll paths over the same ${BETS} even-money bets at win probability ${pPct}% (full Kelly ${fmtPct(
          kelly,
        )}), plotted on a log scale. ${halfLabel} ends at ${fmtMult(
          finalHalf,
        )} the starting bankroll, ${fullLabel} at ${fmtMult(
          finalFull,
        )}, and ${overLabel} at ${fmtMult(finalOver)}.`}
      >
        {/* Time axis baseline */}
        <line
          x1={padLeft}
          y1={baseY}
          x2={W - padRight}
          y2={baseY}
          stroke="var(--color-ink-200)"
        />

        {/* Starting-bankroll reference gridline (dashed) */}
        <line
          x1={padLeft}
          y1={startY}
          x2={W - padRight}
          y2={startY}
          stroke="var(--color-ink-200)"
          strokeWidth={1.5}
          strokeDasharray="5 4"
        />
        <text
          x={padLeft - 6}
          y={startY + 3}
          fontSize={10}
          fontWeight={600}
          fill="var(--color-ink-700)"
          textAnchor="end"
        >
          {`${startLabel} 1×`}
        </text>

        {/* The three bankroll curves */}
        {series.map((s) => (
          <path
            key={s.key}
            d={pathToD(s.d)}
            fill="none"
            stroke={s.color}
            strokeWidth={s.width}
            strokeLinejoin="round"
            strokeLinecap="round"
          />
        ))}

        {/* Time-axis ticks */}
        <text
          x={padLeft}
          y={H - 6}
          fontSize={11}
          fill="var(--color-ink-900)"
          textAnchor="start"
        >
          0
        </text>
        <text
          x={W - padRight}
          y={H - 6}
          fontSize={11}
          fill="var(--color-ink-700)"
          textAnchor="end"
        >
          {BETS}
        </text>
      </svg>

      {/* Final-bankroll readouts */}
      <dl className="mt-4 grid grid-cols-3 gap-3 text-sm" aria-live="polite">
        {series.map((s) => (
          <div
            key={s.key}
            className="rounded-card border border-ink-100 bg-surface-sunken/40 px-3 py-2"
          >
            <dt className="flex items-center gap-2 text-ink-500">
              <span
                className="h-2 w-2 rounded-pill"
                style={{ backgroundColor: s.color }}
                aria-hidden="true"
              />
              {s.label}
            </dt>
            <dd
              className="font-mono text-lg font-semibold"
              style={{ color: s.color }}
            >
              {fmtMult(s.final)}
            </dd>
          </div>
        ))}
      </dl>

      {/* Win-probability slider */}
      <div className="mt-4">
        <label
          htmlFor={`${id}-p`}
          className="flex items-center justify-between gap-3 text-sm font-medium text-ink-700"
        >
          <span>{probLabel}</span>
          <span className="font-mono text-brand-600" aria-hidden="true">
            {pPct}%
          </span>
        </label>
        <input
          id={`${id}-p`}
          type="range"
          min={52}
          max={70}
          step={1}
          value={pPct}
          onChange={(e) => setPPct(Number(e.target.value))}
          aria-valuetext={`${pPct}% win probability`}
          className="mt-2 w-full accent-brand-500"
        />
      </div>

      {/* New-sequence button */}
      <div className="mt-4">
        <button
          type="button"
          onClick={() => setSeedBump((s) => s + 1)}
          className="rounded-pill border border-ink-100 bg-surface-50 px-4 py-1.5 text-sm font-medium text-ink-800 shadow-soft transition hover:bg-surface-100"
        >
          {reshuffleLabel}
        </button>
      </div>

      <p className="mt-3 text-sm leading-relaxed text-ink-600">{caption}</p>
    </figure>
  );
}

export default BetSizingPaths;
